# Generated by Django 5.2 on 2025-04-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usecase',
            name='gameplan',
            field=models.FileField(blank=True, null=True, upload_to='usecases/gameplans/'),
        ),
        migrations.AddField(
            model_name='usecase',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='submitted', max_length=20),
        ),
    ]
