# Generated by Django 5.2 on 2025-04-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_hubcategory_hublink'),
    ]

    operations = [
        migrations.AddField(
            model_name='hublink',
            name='click_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
