# Generated by Django 5.2 on 2025-04-14 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_hublink_click_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hublink',
            name='click_count',
        ),
    ]
