# Generated by Django 5.2 on 2025-04-14 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_hubuseractivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerHost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('jumpbox_ip', models.GenericIPAddressField()),
                ('jumpbox_username', models.CharField(max_length=100)),
                ('jumpbox_auth_type', models.CharField(choices=[('pem', 'PEM File'), ('password', 'Password')], max_length=20)),
                ('jumpbox_pem_file', models.FileField(blank=True, null=True, upload_to='keys/')),
                ('jumpbox_password', models.CharField(blank=True, max_length=255, null=True)),
                ('target_ip', models.GenericIPAddressField()),
                ('target_username', models.CharField(max_length=100)),
                ('target_password', models.CharField(blank=True, max_length=255, null=True)),
                ('target_auth_type', models.CharField(choices=[('pem', 'PEM File'), ('password', 'Password')], max_length=20)),
                ('target_pem_file', models.FileField(blank=True, null=True, upload_to='keys/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
