# Generated by Django 5.2 on 2025-04-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_serverhost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usecase',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('deployed', 'Deployed')], default='submitted', max_length=20),
        ),
    ]
