# Generated by Django 5.2 on 2025-04-15 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_jumpbox_auth_type_serverhost_auth_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=100)),
                ('error_name', models.CharField(max_length=255)),
                ('stack_trace', models.TextField()),
                ('fixed', models.BooleanField(default=False)),
                ('fix_summary', models.TextField(blank=True, null=True)),
                ('doc_link', models.URLField(blank=True, null=True)),
                ('commit_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fixed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
